const CONFIG={API_BASE_URL:"https://word-dkng.onrender.com"};
const $=id=>document.getElementById(id);
const editor=$("editor"),fileInput=$("fileInput"),mediaInput=$("mediaInput"),fileName=$("fileName"),statusEl=$("status")||$("statusText"),messages=$("messages"),promptEl=$("prompt"),sendBtn=$("sendBtn"),downloadBtn=$("downloadBtn"),newBtn=$("newBtn"),topFileName=$("topFileName"),saveState=$("saveState"),dropZone=$("dropZone");
let currentFileName="Yangi AI hujjat.docx",currentDocumentId="",currentFileHandle=null,imageSeq=0;
const mediaMap=new Map();
const api=p=>String(CONFIG.API_BASE_URL||"").replace(/\/+$/g,"")+p;
function setStatus(t){if(statusEl)statusEl.textContent=t;if(saveState)saveState.textContent=t}
function say(t,r="ai"){if(!messages||!t)return;const d=document.createElement("div");d.className=`bubble ${r}`;d.textContent=t;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
async function readResponse(r){const type=r.headers.get("content-type")||"";if(type.includes("application/json")){const d=await r.json();if(!r.ok)throw new Error(d.error||`Server xatosi (${r.status})`);return d}if(!r.ok)throw new Error((await r.text().catch(()=>""))||`Server xatosi (${r.status})`);return r}
function rememberFile(n){currentFileName=n||"Yangi AI hujjat.docx";if(fileName)fileName.textContent=currentFileName;if(topFileName)topFileName.textContent=currentFileName}
function closeFiles(){const p=$("filesPanel");if(p)p.classList.remove("open")}
function setPlainText(text){if(!editor)return;editor.innerHTML="";for(const line of String(text||"").split(/\r?\n/)){const p=document.createElement("div");p.textContent=line;editor.appendChild(p)}}
function dataUrlFromFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=()=>rej(r.error||new Error("Rasm o‘qilmadi"));r.readAsDataURL(file)})}
function createMedia(id,caption=""){const x=mediaMap.get(id);if(!x)return null;const wrap=document.createElement("div");wrap.className="word-media";wrap.dataset.imageId=id;const img=document.createElement("img");img.src=x.dataUrl;img.alt=x.name||"Rasm";img.draggable=false;const cap=document.createElement("div");cap.className="word-media-caption";cap.contentEditable="true";cap.spellcheck=true;cap.textContent=caption;cap.dataset.placeholder="Rasm ostiga ma’lumot yozing...";wrap.append(img,cap);return wrap}
function editorForAI(){if(!editor)return"";const out=[];for(const n of [...editor.childNodes]){if(n.nodeType===1&&n.classList.contains("word-media")){out.push(`[[IMAGE:${n.dataset.imageId}]]`);const cap=n.querySelector(".word-media-caption")?.innerText.trim();if(cap)out.push(cap)}else{const t=n.innerText??n.textContent??"";if(String(t).trim())out.push(String(t))}}return out.join("\n")}
function savePayload(){if(!editor)return{text:"",images:[]};const text=[],images=[];for(const n of [...editor.childNodes]){if(n.nodeType===1&&n.classList.contains("word-media")){const id=n.dataset.imageId,x=mediaMap.get(id);if(x)images.push({type:"image",dataUrl:x.dataUrl,caption:n.querySelector(".word-media-caption")?.innerText.trim()||""});continue}const t=n.innerText??n.textContent??"";if(String(t).trim())text.push(String(t))}return{text:text.join("\n"),images}}
function appendText(text){for(const line of String(text||"").split(/\r?\n/)){const p=document.createElement("div");p.textContent=line;editor.appendChild(p)}}
function rebuildFromAI(text){const re=/\[\[IMAGE:([^\]]+)\]\]/g,v=String(text||"");editor.innerHTML="";let last=0,m;while((m=re.exec(v))){appendText(v.slice(last,m.index));const wrap=createMedia(m[1]);if(wrap)editor.appendChild(wrap);last=re.lastIndex}appendText(v.slice(last))}

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open("ai-word-studio",1);r.onupgradeneeded=()=>r.result.createObjectStore("handles");r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putHandle(id,h){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction("handles","readwrite");tx.objectStore("handles").put(h,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch{}}
async function getHandle(id){try{const db=await openDB();const v=await new Promise((res,rej)=>{const tx=db.transaction("handles","readonly"),r=tx.objectStore("handles").get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});db.close();return v}catch{return null}}
async function permission(h){if(!h?.queryPermission)return true;let p=await h.queryPermission({mode:"readwrite"});if(p!=="granted"&&h.requestPermission)p=await h.requestPermission({mode:"readwrite"});return p==="granted"}

async function loadRecents(mode="files"){const panel=$("filesPanel"),body=$("filesBody"),title=$("filesTitle");if(!panel||!body)return;title.textContent=mode==="favorites"?"★ Sevimlilar":"📁 Mening fayllarim · Recents";body.innerHTML='<div class="file-loading">Yuklanmoqda...</div>';panel.classList.add("open");try{const d=await readResponse(await fetch(api("/api/files"),{cache:"no-store"}));let list=d.files||[];if(mode==="favorites")list=list.filter(x=>x.favorite);body.innerHTML="";if(!list.length){body.innerHTML='<div class="file-empty"><b>Hozircha fayl yo‘q</b><span>Word fayl oching — shu yerda ko‘rinadi.</span></div>';return}list.forEach(item=>{const row=document.createElement("div");row.className="file-card";const info=document.createElement("div");info.className="file-info";const s=document.createElement("strong");s.textContent=item.name;const sm=document.createElement("span");sm.textContent=new Date(item.updatedAt).toLocaleString("uz-UZ");info.append(s,sm);const actions=document.createElement("div");actions.className="file-actions";const fav=document.createElement("button");fav.type="button";fav.textContent=item.favorite?"★":"☆";fav.onclick=async e=>{e.stopPropagation();await fetch(api(`/api/files/${encodeURIComponent(item.id)}/favorite`),{method:"POST"});loadRecents(mode)};const down=document.createElement("button");down.type="button";down.textContent="↓";down.onclick=e=>{e.stopPropagation();const a=document.createElement("a");a.href=api(`/api/files/${encodeURIComponent(item.id)}/download`);a.download=item.name;a.click()};actions.append(fav,down);row.onclick=()=>openSavedFile(item);row.append(info,actions);body.appendChild(row)})}catch{body.innerHTML='<div class="file-empty"><b>Fayllar yuklanmadi</b><span>Serverga ulanishni tekshiring.</span></div>'}}
async function openSavedFile(item){try{setStatus("Fayl ochilmoqda...");const d=await readResponse(await fetch(api(`/api/files/${encodeURIComponent(item.id)}`),{cache:"no-store"}));currentDocumentId=d.documentId;rememberFile(d.fileName);currentFileHandle=await getHandle(item.id);if(currentFileHandle&&!await permission(currentFileHandle))currentFileHandle=null;mediaMap.clear();setPlainText(d.text||"");closeFiles();setStatus("Fayl ochildi")}catch(e){setStatus("Xatolik");say(`❌ ${e.message}`)}}
async function chooseWord(){try{if(window.showOpenFilePicker){const [h]=await window.showOpenFilePicker({multiple:false,types:[{description:"Word",accept:{"application/vnd.openxmlformats-officedocument.wordprocessingml.document":[".docx"]}}]});currentFileHandle=h;return h.getFile()}fileInput?.click();return null}catch(e){if(e?.name!=="AbortError")say("❌ Word faylini tanlashda xato.");return null}}
async function uploadWord(file){if(!file)return;try{const fd=new FormData();fd.append("file",file);setStatus("Word ochilmoqda...");const d=await readResponse(await fetch(api("/api/extract"),{method:"POST",body:fd}));currentDocumentId=d.documentId;rememberFile(d.fileName||file.name);if(currentFileHandle)await putHandle(currentDocumentId,currentFileHandle);mediaMap.clear();setPlainText(d.text||"");closeFiles();setStatus("Word ulandi");say(`✅ ${file.name} ochildi.`)}catch(e){setStatus("Word xatosi");say(`❌ ${e.message}`)}}
function setupWord(){const trigger=document.querySelector(".top-actions label:first-of-type");trigger?.addEventListener("click",async e=>{if(e.target?.tagName==="INPUT")return;e.preventDefault();e.stopPropagation();const f=await chooseWord();if(f)await uploadWord(f)});fileInput?.addEventListener("change",async()=>{const f=fileInput.files?.[0];if(f){currentFileHandle=null;await uploadWord(f)}fileInput.value=""})}
async function saveWord(){if(!currentDocumentId){say("⚠️ Avval Word faylini oching.");return}setStatus("Saqlanmoqda...");try{const p=savePayload();const d=await readResponse(await fetch(api("/api/save"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:currentDocumentId,text:p.text,images:p.images})}));if(currentFileHandle){if(!(await permission(currentFileHandle)))throw new Error("Word fayliga yozish ruxsati berilmadi.");const r=await fetch(api(`/api/files/${encodeURIComponent(currentDocumentId)}/download`),{cache:"no-store"});if(!r.ok)throw new Error("Saqlangan Word nusxasini olishda xato.");const w=await currentFileHandle.createWritable();await w.write(await r.blob());await w.close()}setStatus("Saqlandi");say(`💾 ${d.fileName} saqlandi.`)}catch(e){setStatus("Saqlash xatosi");if(/NoModificationAllowed|Access|Permission|denied|locked|busy/i.test(String(e.message)))say("⚠️ Word fayli hozir boshqa dasturda ochiq yoki bloklangan. Word’ni yoping va Saqlashni yana bosing.");else say(`❌ ${e.message}`)}}

async function addImage(dataUrl,name="AI rasmi",caption=""){const id=`img-${++imageSeq}-${Date.now()}`;mediaMap.set(id,{dataUrl,name});const wrap=createMedia(id,caption);if(wrap){editor.appendChild(wrap);wrap.querySelector(".word-media-caption")?.focus();setStatus("Rasm qo‘shildi");return id}return null}
async function addMedia(file){if(!file?.type?.startsWith("image/"))return;try{await addImage(await dataUrlFromFile(file),file.name);say(`🖼️ ${file.name} qo‘shildi.`)}catch(e){say(`❌ ${e.message}`)}}
function setupMedia(){$("mediaBtn")?.addEventListener("click",e=>{e.preventDefault();mediaInput?.click()});$("chatAttach")?.addEventListener("click",e=>{e.preventDefault();mediaInput?.click()});mediaInput?.addEventListener("change",()=>{[...(mediaInput.files||[])].forEach(addMedia);mediaInput.value=""})}
async function generateImage(prompt){setStatus("Rasm yaratilmoqda...");try{const d=await readResponse(await fetch(api("/api/image"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})}));await addImage(d.dataUrl,"AI rasmi");say("✅ Rasm yaratildi va hujjatga qo‘shildi.");setStatus("Rasm tayyor")}catch(e){say(`❌ ${e.message}`);if(/OPENAI_API_KEY/i.test(e.message))say("ℹ️ Render → Environment → OPENAI_API_KEY ni qo‘shing va backendni qayta deploy qiling.");setStatus("Rasm xatosi")}}
function isImageRequest(t){return /\b(rasm|photo|surat|image)\b/i.test(t)&&/(yarat|qil|chiz|qo['’]?sh|create|generate|draw|make)/i.test(t)}
async function sendPrompt(text=promptEl?.value){const instruction=String(text||"").trim();if(!instruction)return;say(instruction,"user");if(promptEl)promptEl.value="";if(isImageRequest(instruction)){if(sendBtn)sendBtn.disabled=true;await generateImage(instruction.replace(/^(rasm|photo|surat|image)\s*(yarat|qil|chiz|qo['’]?sh)?[:\-]?/i,"").trim()||instruction);if(sendBtn)sendBtn.disabled=false;return}if(sendBtn)sendBtn.disabled=true;setStatus("AI ishlayapti...");try{const d=await readResponse(await fetch(api("/api/chat"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:currentDocumentId,documentText:editorForAI(),instruction})}));if(d.changed&&d.editedDocument)rebuildFromAI(d.editedDocument);if(d.answer)say(d.answer);if(d.changed)setStatus("AI tahrirladi")}catch(e){setStatus("AI xatosi");say(`❌ ${e.message}`)}finally{if(sendBtn)sendBtn.disabled=false}}
sendBtn?.addEventListener("click",e=>{e.preventDefault();sendPrompt()});promptEl?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendPrompt()}});document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>sendPrompt(b.dataset.prompt)));
downloadBtn?.addEventListener("click",async e=>{e.preventDefault();if(!currentDocumentId){say("⚠️ Avval Word faylini oching.");return}try{const p=savePayload();const r=await readResponse(await fetch(api("/api/export"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:currentDocumentId,text:p.text,images:p.images})}));const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=currentFileName;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);say(`✅ ${currentFileName} yuklab olindi.`)}catch(e){say(`❌ ${e.message}`)}});
$("imageBtn")?.addEventListener("click",e=>{e.preventDefault();if(promptEl){promptEl.value="Rasm yarat: ";promptEl.focus()}});
newBtn?.addEventListener("click",e=>{e.preventDefault();if(editor)editor.innerHTML="";currentDocumentId="";currentFileHandle=null;mediaMap.clear();rememberFile("Yangi AI hujjat.docx");closeFiles();setStatus("Yangi hujjat")});
$("saveBtn")?.addEventListener("click",e=>{e.preventDefault();saveWord()});
function setupToolbar(){const tools=[...document.querySelectorAll(".toolbar-left .tool")],actions=["undo","redo","bold","italic","underline","justifyLeft","justifyCenter","justifyRight"],names=["Bekor qilindi.","Qayta tiklandi.","Qalin yozuv yoqildi.","Kursiv yozuv yoqildi.","Tagiga chizildi.","Chapga tekislandi.","Markazga tekislandi.","O‘ngga tekislandi."];tools.forEach((b,i)=>b.addEventListener("click",e=>{e.preventDefault();editor?.focus();document.execCommand(actions[i],false,null);setStatus("O‘zgartirildi");say(`✅ ${names[i]}`)}))}
function setupEditor(){editor?.addEventListener("input",()=>setStatus("O‘zgartirildi"));editor?.addEventListener("click",e=>{const m=e.target?.closest?.(".word-media");if(m)m.querySelector(".word-media-caption")?.focus()});if(dropZone&&editor){editor.addEventListener("dragover",e=>{e.preventDefault();dropZone.style.display="grid"});editor.addEventListener("dragleave",()=>dropZone.style.display="none");editor.addEventListener("drop",e=>{e.preventDefault();dropZone.style.display="none";[...(e.dataTransfer?.files||[])].forEach(addMedia)})}}
function setupNavigation(){const buttons=[...document.querySelectorAll(".nav button")];buttons.forEach(b=>b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();buttons.forEach(x=>x.classList.remove("active"));b.classList.add("active");const t=b.textContent||"";if(/Mening fayllarim|Yaqinda/i.test(t))loadRecents("files");else if(/Sevimlilar/i.test(t))loadRecents("favorites");else if(/Bosh sahifa/i.test(t))closeFiles()}));$("filesTopBtn")?.addEventListener("click",e=>{e.preventDefault();loadRecents("files")});$("closeFiles")?.addEventListener("click",e=>{e.preventDefault();closeFiles()})}
async function checkBackend(){try{const d=await readResponse(await fetch(api("/health"),{cache:"no-store"}));setStatus(d.aiConfigured?"AI ulangan":"AI kalit sozlanmagan")}catch{setStatus("Backend ulanmagan")}}
function lockChat(){const s=document.createElement("style");s.textContent=`.chat{grid-row:2!important;height:calc(100vh - 68px)!important;min-height:0!important;display:grid!important;grid-template-rows:auto minmax(0,1fr) auto auto!important;overflow:hidden!important}.messages{min-height:0!important;overflow-y:auto!important}.composer{position:static!important;flex:none!important;align-self:end!important;width:100%!important;margin:0!important;bottom:auto!important;top:auto!important}.suggestions{position:static!important;flex:none!important;max-height:82px!important;overflow:auto!important}.word-media{display:block;margin:20px 0;padding:12px;border:1px solid #dfe5ed;background:#fff;border-radius:12px}.word-media img{display:block;max-width:100%;max-height:520px;object-fit:contain;margin:auto}.word-media-caption{margin-top:10px;min-height:28px;padding:8px 10px;border:1px dashed #cbd5e1;border-radius:8px;color:#334155;outline:none}.word-media-caption:empty:before{content:attr(data-placeholder);color:#94a3b8}@media(max-width:1200px){.chat{display:none!important}}@media(max-width:800px){.chat{display:grid!important;height:calc(100vh - 126px)!important;min-height:560px!important}.composer{position:static!important}}`;document.head.appendChild(s)}
function init(){lockChat();setupNavigation();setupWord();setupMedia();setupToolbar();setupEditor();checkBackend()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();