const CONFIG={API_BASE_URL:"https://word-dkng.onrender.com"};
const $=id=>document.getElementById(id);
const editor=$("editor"),fileInput=$("fileInput"),mediaInput=$("mediaInput"),fileName=$("fileName"),statusEl=$("status")||$("statusText"),messages=$("messages"),promptEl=$("prompt"),sendBtn=$("sendBtn"),downloadBtn=$("downloadBtn"),newBtn=$("newBtn"),topFileName=$("topFileName"),saveState=$("saveState"),dropZone=$("dropZone");
let currentFileName="AI-Word-Hujjat.docx",currentDocumentId="",originalWordFileLoaded=false;
const USER_KEY="ai_word_user";
function api(path){return String(CONFIG.API_BASE_URL||"").replace(/\/+$/ ,"")+path}
function setStatus(t){if(statusEl)statusEl.textContent=t;if(saveState)saveState.textContent="● "+t}
function addMessage(text,role="ai"){if(!messages)return;const d=document.createElement("div");d.className=`bubble ${role}`;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
async function readResponse(r){const type=r.headers.get("content-type")||"";if(type.includes("application/json")){const d=await r.json();if(!r.ok)throw new Error(d.error||`Server xatosi (${r.status})`);return d}if(!r.ok)throw new Error((await r.text().catch(()=>""))||`Server xatosi (${r.status})`);return r}
function rememberFile(name){currentFileName=name;if(fileName)fileName.textContent=name;if(topFileName)topFileName.textContent=name}
function getUser(){try{const u=JSON.parse(localStorage.getItem(USER_KEY)||"null");return u&&String(u.username||"").trim()?u:null}catch{return null}}
function setAuthButtons(user){const ids=["loginBtn","signupBtn","loginTopBtn","signupTopBtn"];ids.forEach(id=>{const b=$(id);if(b)b.style.display=user?"none":""});let badge=$("userBadge");if(user){if(!badge){badge=document.createElement("button");badge.id="userBadge";badge.className="user-badge";badge.type="button";$("loginTopBtn")?.parentElement?.appendChild(badge)}badge.textContent=`👤 ${user.username}`;badge.style.display="inline-flex";badge.onclick=openAuth}else if(badge)badge.style.display="none"}
function applyUser(user,show=false){if(!user)return;const name=String(user.username).trim();$("profileName")&&( $("profileName").textContent=name);$("profileEmail")&&($("profileEmail").textContent=user.email||"AI Word Studio");$("avatar")&&($("avatar").textContent=name.charAt(0).toUpperCase());$("welcomeUser")&&($("welcomeUser").textContent=`Salom, ${name}! 👋`);document.querySelectorAll("[data-user-greeting]").forEach(e=>e.textContent=`Salom, ${name}!`);setAuthButtons(user);if(show)addMessage(`👋 Xush kelibsiz, ${name}!`)}
function closeAuth(){const m=$("authModal");if(m){m.classList.remove("open");m.classList.add("hidden")}}
function saveUser(){const name=$("authName")?.value.trim();const email=$("authEmail")?.value.trim()||"";if(!name){$("authName")?.focus();return false}const user={username:name,email};localStorage.setItem(USER_KEY,JSON.stringify(user));applyUser(user,true);closeAuth();return true}
function bindAuth(){const m=$("authModal");if(!m)return;$("closeAuth")?.addEventListener("click",closeAuth);m.addEventListener("click",e=>{if(e.target===m)closeAuth()});const form=$("authForm");if(form&&!form.dataset.bound){form.dataset.bound="1";form.addEventListener("submit",e=>{e.preventDefault();saveUser()})}const submit=$("authSubmit");if(submit&&!submit.dataset.bound){submit.dataset.bound="1";submit.addEventListener("click",e=>{if(form)e.preventDefault();saveUser()})}}
function ensureAuthUI(){bindAuth();const m=$("authModal");if(m)return m;const x=document.createElement("div");x.id="authModal";x.className="modal hidden";x.innerHTML='<div class="modal-card auth-card"><button id="closeAuth" type="button">✕</button><h2 id="authTitle">AI Word Studio</h2><p id="authDescription">Davom etish uchun ismingizni kiriting.</p><form id="authForm"><input id="authName" maxlength="40" placeholder="Ismingiz yoki username" required><input id="authEmail" type="email" placeholder="Email (ixtiyoriy)"><button id="authSubmit" type="submit">Kirish / Ro‘yxatdan o‘tish</button></form></div></div>';document.body.appendChild(x);bindAuth();return x}
function openAuth(){const m=ensureAuthUI();const u=getUser();if(u){$("authName")&&($("authName").value=u.username);$("authEmail")&&($("authEmail").value=u.email||"");$("authTitle")&&($("authTitle").textContent=`Salom, ${u.username}!`);$("authDescription")&&($("authDescription").textContent="Username saqlangan. Xohlasangiz o‘zgartiring.")}else{$("authTitle")&&($("authTitle").textContent="AI Word Studio");$("authDescription")&&($("authDescription").textContent="Davom etish uchun ismingizni kiriting.")}m.classList.remove("hidden");m.classList.add("open")}
function requireAccount(section){const u=getUser();if(u)return true;openAuth();$("authTitle")&&($("authTitle").textContent=`🔐 ${section}`);$("authDescription")&&($("authDescription").textContent="Bu bo‘lim uchun ro‘yxatdan o‘ting yoki kiring. Word, AI va tahrirlash esa login qilmasdan ishlaydi.");return false}
function setupAccountSections(){document.querySelectorAll(".nav button").forEach(b=>{const t=b.textContent||"";if(/Mening fayllarim|Yaqinda|Sevimlilar/i.test(t))b.addEventListener("click",e=>{e.preventDefault();if(requireAccount(t.replace(/[▣◌★]/g," ").trim()))addMessage("📂 Bo‘lim ochildi.")})});$("filesTopBtn")?.addEventListener("click",e=>{e.preventDefault();if(requireAccount("Mening fayllarim"))addMessage("📁 Fayllaringiz shu yerda.")})}
function setupWord(){if(!fileInput)return;fileInput.addEventListener("click",()=>closeAuth());fileInput.addEventListener("change",async()=>{const file=fileInput.files?.[0];if(!file)return;try{setStatus("Word o‘qilmoqda...");const f=new FormData;f.append("file",file);const d=await readResponse(await fetch(api("/api/extract"),{method:"POST",body:f}));currentDocumentId=d.documentId||"";originalWordFileLoaded=!!currentDocumentId;if(editor)editor.textContent=d.text||"";rememberFile(file.name);setStatus("Word ulandi");addMessage(`✅ ${file.name} ulandi.`)}catch(e){setStatus("Xatolik");addMessage("❌ "+e.message)}finally{fileInput.value=""}});const wordLabel=fileInput.closest("label");wordLabel?.addEventListener("click",()=>{closeAuth();setTimeout(()=>fileInput.click(),0)});}
function addMedia(file){if(!editor)return;const wrap=document.createElement("div");wrap.className="inline-media-wrap";wrap.contentEditable="false";const url=URL.createObjectURL(file);if(file.type.startsWith("image/")){const i=document.createElement("img");i.className="inline-media";i.src=url;wrap.appendChild(i)}else if(file.type.startsWith("video/")){const v=document.createElement("video");v.className="inline-media";v.src=url;v.controls=true;wrap.appendChild(v)}else{const c=document.createElement("div");c.className="file-chip";c.textContent="📎 "+file.name;wrap.appendChild(c)}editor.appendChild(wrap);setStatus("Fayl qo‘shildi")}
mediaInput?.addEventListener("change",()=>{[...(mediaInput.files||[])].forEach(addMedia);mediaInput.value=""});$("chatAttach")?.addEventListener("click",()=>mediaInput?.click());
newBtn?.addEventListener("click",()=>{if(editor)editor.textContent="";currentDocumentId="";originalWordFileLoaded=false;rememberFile("Yangi AI hujjat.docx");setStatus("Yangi hujjat")});
async function sendPrompt(text=promptEl?.value){const instruction=String(text||"").trim();if(!instruction)return;addMessage(instruction,"user");if(promptEl)promptEl.value="";if(sendBtn)sendBtn.disabled=true;setStatus("AI ishlayapti...");try{const d=await readResponse(await fetch(api("/api/chat"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:currentDocumentId,documentText:editor?.textContent||"",instruction})}));if(d.changed){if(editor)editor.textContent=d.editedDocument||editor.textContent;currentDocumentId=d.documentId||currentDocumentId;setStatus("Tahrirlandi")}addMessage("✅ "+(d.answer||"Javob tayyor."))}catch(e){addMessage("❌ "+e.message);setStatus("Xatolik")}finally{if(sendBtn)sendBtn.disabled=false}}
sendBtn?.addEventListener("click",()=>sendPrompt());promptEl?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendPrompt()}});document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>sendPrompt(b.dataset.prompt)));
downloadBtn?.addEventListener("click",async()=>{try{if(!currentDocumentId)throw new Error("Avval .docx Word faylni ulang.");const r=await fetch(api("/api/export"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:currentDocumentId,text:editor?.textContent||"",fileName:currentFileName})});await readResponse(r);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=currentFileName.replace(/\.docx$/i,"")+"-AI.docx";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setStatus("Word yuklandi")}catch(e){addMessage("❌ "+e.message)}});
$("saveBtn")?.addEventListener("click",()=>{setStatus("Saqlangan");addMessage("✓ O‘zgarishlar saqlash uchun tayyor.")});
["loginBtn","signupBtn","loginTopBtn","signupTopBtn"].forEach(id=>$(id)?.addEventListener("click",openAuth));
loadUser();function loadUser(){const u=getUser();if(u)applyUser(u,false);else setAuthButtons(null)}
setupAccountSections();setupWord();
async function checkBackend(){try{const d=await readResponse(await fetch(api("/health"),{cache:"no-store"}));setStatus(d.aiConfigured?"AI ulangan":"AI kalit sozlanmagan")}catch{setStatus("Backend ulanmagan")}}checkBackend();