const CONFIG={API_BASE_URL:"https://word-dkng.onrender.com"};
const editor=document.getElementById("editor"),fileInput=document.getElementById("fileInput"),mediaInput=document.getElementById("mediaInput"),fileName=document.getElementById("fileName"),statusEl=document.getElementById("status"),messages=document.getElementById("messages"),promptEl=document.getElementById("prompt"),sendBtn=document.getElementById("sendBtn"),downloadBtn=document.getElementById("downloadBtn"),newBtn=document.getElementById("newBtn"),attachmentsEl=document.getElementById("attachments");
let currentFileName="AI-Word-Hujjat.docx";let attachments=[];
function api(path){const base=CONFIG.API_BASE_URL.trim().replace(/\/+$/ ,"");if(!base||base.includes("PASTE_YOUR"))throw new Error("Backend URL hali sozlanmagan.");return base+path}
function setStatus(t){statusEl.textContent=t}
function addMessage(text,role="ai"){const d=document.createElement("div");d.className=`bubble ${role}`;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function loading(on){let x=document.getElementById("loading");if(on&&!x){x=document.createElement("div");x.id="loading";x.className="bubble ai";x.textContent="AI yozmoqda...";messages.appendChild(x)}if(!on)x?.remove();messages.scrollTop=messages.scrollHeight}
function formatSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`}
function renderAttachments(){attachmentsEl.innerHTML="";if(!attachments.length){attachmentsEl.innerHTML='<div class="empty-attachments">📎 Qo‘shilgan rasm, video va fayllar shu yerda ko‘rinadi.</div>';return}attachments.forEach((item,index)=>{const card=document.createElement("div");card.className="attachment-card";const preview=document.createElement("div");preview.className="attachment-preview";if(item.type.startsWith("image/")){const img=document.createElement("img");img.src=item.url;img.alt=item.name;preview.appendChild(img)}else if(item.type.startsWith("video/")){const video=document.createElement("video");video.src=item.url;video.controls=true;video.preload="metadata";preview.appendChild(video)}else{preview.innerHTML='<span class="file-icon">📄</span>'}const info=document.createElement("div");info.className="attachment-info";info.innerHTML=`<strong>${item.name}</strong><span>${formatSize(item.size)}</span>`;const remove=document.createElement("button");remove.className="remove-file";remove.type="button";remove.textContent="×";remove.title="Olib tashlash";remove.onclick=()=>{URL.revokeObjectURL(item.url);attachments.splice(index,1);renderAttachments();setStatus("Fayl olib tashlandi")};card.append(preview,info,remove);attachmentsEl.appendChild(card)})}
async function readTextFile(file){if(!/^(text\/|application\/json$)/i.test(file.type)&&!/\.(txt|md|csv|json)$/i.test(file.name))return"";try{return await file.text()}catch{return""}}
fileInput.addEventListener("change",async()=>{const file=fileInput.files?.[0];if(!file)return;try{setStatus("Word o‘qilmoqda...");const f=new FormData;f.append("file",file);const r=await fetch(api("/api/extract"),{method:"POST",body:f}),data=await r.json();if(!r.ok)throw new Error(data.error||"Fayl o‘qilmadi.");editor.value=data.text||"";currentFileName=file.name;fileName.textContent=file.name;setStatus("Ulandi");addMessage(`✅ "${file.name}" Word hujjati ulandi.`)}catch(e){setStatus("Xatolik");addMessage("❌ "+e.message)}finally{fileInput.value=""}});
mediaInput.addEventListener("change",async()=>{const files=Array.from(mediaInput.files||[]);if(!files.length)return;const max=50*1024*1024;let added=0;for(const file of files){if(file.size>max){addMessage(`⚠️ "${file.name}" 50 MB dan katta, qo‘shilmadi.`);continue}const url=URL.createObjectURL(file);const text=await readTextFile(file);attachments.push({name:file.name,size:file.size,type:file.type||"application/octet-stream",url,text});added++}renderAttachments();setStatus(`${added} ta fayl qo‘shildi`);if(added)addMessage(`📎 ${added} ta rasm, video yoki fayl qo‘shildi.`);mediaInput.value=""});
newBtn.addEventListener("click",()=>{editor.value="";attachments.forEach(x=>URL.revokeObjectURL(x.url));attachments=[];renderAttachments();currentFileName="Yangi-AI-Hujjat.docx";fileName.textContent="Yangi AI hujjat.docx";setStatus("Yangi hujjat");addMessage("📝 Yangi bo‘sh hujjat yaratildi.")});
function attachmentContext(){if(!attachments.length)return"Qo‘shilgan fayllar yo‘q.";return attachments.map((x,i)=>`${i+1}. ${x.name} (${x.type||"file"}, ${formatSize(x.size)})${x.text?`\nMatni:\n${x.text.slice(0,12000)}`:""}`).join("\n\n")}
async function sendPrompt(text=promptEl.value){const instruction=text.trim();if(!instruction)return;addMessage(instruction,"user");promptEl.value="";sendBtn.disabled=true;setStatus("AI ishlayapti...");loading(true);try{const r=await fetch(api("/api/chat"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentText:editor.value,instruction,attachments:attachments.map(x=>({name:x.name,type:x.type,size:x.size,text:x.text||""}))})}),data=await r.json();if(!r.ok)throw new Error(data.error||"AI xatosi.");loading(false);if(data.changed){editor.value=data.editedDocument||editor.value;setStatus("Hujjat yangilandi");addMessage("✅ "+(data.answer||"Hujjat yangilandi."))}else{addMessage(data.answer||"Javob tayyor.");setStatus("Tayyor")}}catch(e){loading(false);addMessage("❌ "+e.message);setStatus("Xatolik")}finally{sendBtn.disabled=false}}
sendBtn.addEventListener("click",()=>sendPrompt());promptEl.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendPrompt()}});document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>sendPrompt(b.dataset.prompt)));
downloadBtn.addEventListener("click",async()=>{try{setStatus("Word tayyorlanmoqda...");const r=await fetch(api("/api/export"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:editor.value,fileName:currentFileName})});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.error||"Word yaratilmadi")}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=currentFileName.replace(/\.docx$/i,"")+"-AI.docx";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus("Yuklandi")}catch(e){addMessage("❌ "+e.message);setStatus("Xatolik")}});
renderAttachments();
