(()=>{
const $=id=>document.getElementById(id),E=$("editor"),P=$("prompt"),B=$("sendBtn");if(!E||!P||!B)return;
const norm=s=>String(s??"").toLowerCase().replace(/[‘’ʻʼ`]/g,"'").replace(/\s+/g," ").trim(),msg=(t,r="ai")=>window.message?.(t,r),status=t=>window.status?.(t);
const getBox=()=>E.querySelector(".matrix-diagram"),getTable=()=>getBox()?.querySelector("table.matrix-table");
const flash=x=>{x?.classList.remove("matrix-chat-updated");if(x){void x.offsetWidth;x.classList.add("matrix-chat-updated")}};
const setSize=(w,h)=>{const x=getBox();if(!x)return false;x.dataset.diagramWidth=w;x.dataset.diagramHeight=h;x.style.width=w+"px";x.style.minHeight=h+"px";x.style.maxWidth="none";x.style.overflow="auto";x.querySelectorAll("td,th").forEach(c=>c.style.minWidth=Math.max(90,Math.floor(w/8))+"px");status(`Diagramma ${w}×${h} ga o‘zgartirildi`);return true};
const addRow=(name="Yangi ma’lumot")=>{const t=getTable();if(!t)return false;const n=t.rows[0]?.cells.length||2,r=document.createElement("tr");for(let i=0;i<n;i++){const c=document.createElement(i?"td":"th");c.contentEditable="true";c.textContent=i?"":name;r.appendChild(c)}t.appendChild(r);return true};
const addCol=(name="Yangi bo‘lim")=>{const t=getTable();if(!t)return false;[...t.rows].forEach((r,i)=>{const c=document.createElement(i?"td":"th");c.contentEditable="true";c.textContent=i?"":name;r.appendChild(c)});return true};
const allCells=()=>{const t=getTable();return t?[...t.rows].flatMap((r,i)=>[...r.cells].filter((_,j)=>i>0&&j>0)):[]};
const command=raw=>{const q=norm(raw),box=getBox(),t=getTable();if(!box||!t)return false;
 let m=q.match(/(\d{2,5})\s*[x×]\s*(\d{2,5})/);if(m&&setSize(+m[1],+m[2])){msg(`✅ Diagramma aniq ${m[1]}×${m[2]} px qilindi.`);return true}
 if(/juda katta|katta diagramma|very large|large detailed/.test(q)){let added=0;for(let i=t.rows.length;i<31;i++){addRow(`Bo‘lim ${i}`);added++}for(let i=t.rows[0].cells.length;i<9;i++){addCol(`Yo‘nalish ${i}`)}box.style.width="2600px";box.style.minHeight="1800px";box.style.maxWidth="none";box.style.overflow="auto";msg(`✅ Katta diagramma yaratildi: ${t.rows.length-1} ta bo‘lim va ${t.rows[0].cells.length-1} ta yo‘nalish.`);status("Katta diagramma tayyor");return true}
 m=q.match(/(?:yana\s+)?(\d+)\s*(?:ta\s+)?(?:ma['’]?lumot|bo['’]?lim|node|element|qator|satr)/);if(m){const n=Math.min(200,+m[1]);for(let i=0;i<n;i++)addRow(`Yangi element ${i+1}`);msg(`✅ ${n} ta haqiqiy diagramma elementi qo‘shildi.`);status("Diagramma yangilandi");return true}
 if(/diagrammaga|diagrammaga|diagramga/.test(q)&&/ma['’]?lumot|bo['’]?lim|node|element/.test(q)&&/qo['’]?sh/.test(q)){addRow();msg("✅ Diagrammaga yangi element qo‘shildi.");status("Diagramma yangilandi");return true}
 if(/hammasiga|barchasiga|har biriga|all|every/.test(q)){const cells=allCells();let text=q.replace(/hammasiga|barchasiga|har biriga|all|every/g,"").replace(/qo['’]?sh.*/i,"").trim();let value=text||"+ ma’lumot";cells.forEach(c=>{c.textContent=(c.textContent?c.textContent+" ":"")+value;flash(c)});msg(`✅ O‘zgarish barcha ${cells.length} ta mos elementga qo‘llandi.`);status("Barcha elementlar yangilandi");return true}
 m=q.match(/(.+?)ning\s+(yoshi|ishi|kasbi|puli|maoshi|daromadi)\s+(.+?)(?:ga|qil|bo['’]?lsin|o['’]?zgartir)?$/);if(m){const target=norm(m[1]),field=norm(m[2]),value=m[3].trim();let col=-1,row=-1;for(let c=1;c<t.rows[0].cells.length;c++)if(norm(t.rows[0].cells[c].innerText).includes(target)){col=c;break}for(let r=1;r<t.rows.length;r++)if(norm(t.rows[r].cells[0].innerText).includes(field)){row=r;break}if(col>0&&row>0){t.rows[row].cells[col].textContent=value;flash(t.rows[row].cells[col]);msg(`✅ ${m[1]}ning ${field} o‘zgartirildi.`);status("Diagramma yangilandi");return true}}
 if(/yana\s+bir|yangi/.test(q)&&/odam|inson|shaxs/.test(q)){let n=(q.match(/odam\s+(.+?)\s+qo['’]?sh/)||[])[1]||"Yangi odam";addCol(n);msg(`✅ ${n} uchun diagramma ustuni qo‘shildi.`);status("Diagramma yangilandi");return true}
 return false};
const capture=e=>{if(e.type==="keydown"&&!(e.key==="Enter"&&!e.shiftKey))return;if(e.type==="click"&&e.target!==B)return;const q=P.value.trim();if(!q||!getBox())return;if(!command(q))return;e.preventDefault();e.stopImmediatePropagation();msg(q,"user");P.value=""};B.addEventListener("click",capture,true);P.addEventListener("keydown",capture,true);
const css=document.createElement("style");css.textContent='.matrix-diagram{box-sizing:border-box!important}.matrix-chat-updated{animation:mxp .45s ease}@keyframes mxp{50%{outline:3px solid #6b8cff}}';document.head.appendChild(css);
})();
