(()=>{
const $=id=>document.getElementById(id),E=$("editor"),P=$("prompt"),B=$("sendBtn");if(!E||!P||!B)return;
const norm=s=>String(s??"").toLowerCase().replace(/[‘’ʻʼ`]/g,"'").replace(/\s+/g," ").trim(),msg=(t,r="ai")=>window.message?.(t,r),status=t=>window.status?.(t),box=()=>E.querySelector(".matrix-diagram"),table=()=>box()?.querySelector("table.matrix-table"),clean=s=>norm(s).replace(/[.!?]+$/g,"");
const flash=c=>{if(!c)return;c.classList.remove("matrix-chat-updated");void c.offsetWidth;c.classList.add("matrix-chat-updated")};
const findRow=label=>{const t=table(),q=norm(label).replace(/satr(ini)?|qator(ini)?/g,"").trim();if(!t)return-1;for(let i=1;i<t.rows.length;i++){const v=norm(t.rows[i].cells[0]?.innerText).replace(/satr|qator/g,"").trim();if(v===q||v.includes(q)||q.includes(v))return i}return-1};
const findCol=name=>{const t=table(),q=norm(name).replace(/ustun(ini)?/g,"").trim();if(!t?.rows.length)return-1;for(let i=1;i<t.rows[0].cells.length;i++){const v=norm(t.rows[0].cells[i].innerText).trim();if(v===q||v.includes(q)||q.includes(v))return i}return-1};
const setSize=(w,h)=>{const x=box();if(!x)return false;x.dataset.diagramWidth=w;x.dataset.diagramHeight=h;x.style.width=w+"px";x.style.minHeight=h+"px";x.style.maxWidth="none";x.style.overflow="auto";status(`Diagramma ${w}×${h} ga o‘zgartirildi`);return true};
const addRow=(name="Yangi ma’lumot")=>{const t=table();if(!t)return false;const n=t.rows[0]?.cells.length||2,r=document.createElement("tr");for(let i=0;i<n;i++){const c=document.createElement(i?"td":"th");c.contentEditable="true";c.spellcheck=true;c.textContent=i?"":name;r.appendChild(c)}t.appendChild(r);return true};
const addCol=(name="Yangi odam")=>{const t=table();if(!t)return false;[...t.rows].forEach((r,i)=>{const c=document.createElement(i?"td":"th");c.contentEditable="true";c.spellcheck=true;c.textContent=i?"":name;r.appendChild(c)});return true};
const deleteRow=i=>{const t=table();if(!t||i<1||t.rows.length<=2)return false;t.deleteRow(i);return true};
const deleteCol=i=>{const t=table();if(!t||i<1||t.rows[0].cells.length<=2)return false;[...t.rows].forEach(r=>r.deleteCell(i));return true};
const allCells=()=>{const t=table();return t?[...t.rows].flatMap((r,i)=>i>0?[...r.cells].slice(1):[]):[]};
function command(raw){const q=clean(raw),t=table(),x=box();if(!t||!x)return false;
let m=q.match(/(\d{2,5})\s*[x×]\s*(\d{2,5})/);if(m&&setSize(+m[1],+m[2])){msg(`✅ Diagramma aniq ${m[1]}×${m[2]} px qilindi.`);return true}
if(/juda katta|katta diagramma|very large|large detailed/.test(q)){while(t.rows.length<31)addRow(`Bo‘lim ${t.rows.length}`);while(t.rows[0].cells.length<9)addCol(`Yo‘nalish ${t.rows[0].cells.length}`);x.style.width="2600px";x.style.minHeight="1800px";x.style.maxWidth="none";x.style.overflow="auto";msg(`✅ Katta diagramma tayyor: ${t.rows.length-1} ta bo‘lim, ${t.rows[0].cells.length-1} ta yo‘nalish.`);status("Katta diagramma tayyor");return true}
m=q.match(/(?:yana\s+)?(\d+)\s*(?:ta\s+)?(?:ma['’]?lumot|bo['’]?lim|node|element|qator|satr)/);if(m){const n=Math.min(200,+m[1]);for(let i=0;i<n;i++)addRow(`Yangi element ${i+1}`);msg(`✅ ${n} ta haqiqiy diagramma elementi qo‘shildi.`);status("Diagramma yangilandi");return true}
if(/diagrammaga|diagramga/.test(q)&&/ma['’]?lumot|bo['’]?lim|node|element/.test(q)&&/qo['’]?sh/.test(q)){addRow();msg("✅ Diagrammaga yangi element qo‘shildi.");status("Diagramma yangilandi");return true}
if(/yana\s+bir|yangi/.test(q)&&/odam|inson|shaxs/.test(q)&&/qo['’]?sh/.test(q)){const match=q.match(/(?:odam|inson|shaxs)\s+(.+?)\s+qo['’]?sh/);const n=match?.[1]?.trim()||`Yangi odam ${t.rows[0].cells.length}`;addCol(n);msg(`✅ ${n} diagrammaga qo‘shildi.`);status("Diagramma yangilandi");return true}
if(/hammasiga|barchasiga|har biriga|all|every/.test(q)){const cells=allCells();let value=q.replace(/hammasiga|barchasiga|har biriga|all|every/g,"").replace(/qo['’]?sh.*/i,"").replace(/diagrammaga|diagramga/g,"").trim()||"+ ma’lumot";cells.forEach(c=>{c.textContent=(c.textContent?c.textContent+" ":"")+value;flash(c)});msg(`✅ O‘zgarish barcha ${cells.length} ta diagramma katagiga qo‘llandi.`);status("Barcha elementlar yangilandi");return true}
if(/o['’]?chir|delete|remove/.test(q)&&/satr|qator|row/.test(q)){let label=(q.match(/(.+?)\s+(?:satr|qator)(?:ni)?\s*(?:o['’]?chir|delete|remove)/)||[])[1];if(!label)label=(q.match(/(.+?)\s+(?:o['’]?chir|delete|remove)\s+(?:satr|qator)/)||[])[1];const i=findRow(label||"");if(i>0&&deleteRow(i)){msg(`✅ “${t.rows[i]?.cells[0]?.innerText||label}” satri o‘chirildi.`);status("Diagramma yangilandi");return true}if(deleteRow(t.rows.length-1)){msg("✅ Oxirgi satr o‘chirildi.");status("Diagramma yangilandi");return true}return true}
if(/o['’]?chir|delete|remove/.test(q)&&/(odam|inson|shaxs|ustun|column)/.test(q)){let name=(q.match(/(.+?)\s+(?:ustun(?:ini)?|odam(?:ni)?|inson(?:ni)?|shaxs(?:ni)?)\s*(?:o['’]?chir|delete|remove)/)||[])[1];if(!name)name=(q.match(/(?:odam|inson|shaxs|ustun)\s+(.+?)\s+(?:o['’]?chir|delete|remove)/)||[])[1];const i=findCol(name||"");if(i>0&&deleteCol(i)){msg(`✅ “${t.rows[0].cells[i].innerText}” o‘chirildi.`);status("Diagramma yangilandi");return true}if(deleteCol(t.rows[0].cells.length-1)){msg("✅ Oxirgi ustun o‘chirildi.");status("Diagramma yangilandi");return true}return true}
m=q.match(/(.+?)ni\s+(\d+)\s*yosh(?:ga|\s+qil)?$/);if(m){const c=findCol(m[1]),r=findRow("yoshi");if(c>0&&r>0){t.rows[r].cells[c].textContent=m[2];flash(t.rows[r].cells[c]);msg(`✅ ${m[1]}ning yoshi ${m[2]} ga o‘zgartirildi.`);status("Diagramma yangilandi");return true}}
m=q.match(/(.+?)ning\s+(yoshi|ishi|kasbi|puli|maoshi|daromadi)\s+(.+?)(?:ga|qil|bo['’]?lsin|o['’]?zgartir)?$/);if(m){const c=findCol(m[1]),r=findRow(m[2]);if(c>0&&r>0){t.rows[r].cells[c].textContent=m[3].trim();flash(t.rows[r].cells[c]);msg(`✅ ${m[1]}ning ${m[2]} o‘zgartirildi.`);status("Diagramma yangilandi");return true}}
return false}
const capture=e=>{if(e.type==="keydown"&&!(e.key==="Enter"&&!e.shiftKey))return;if(e.type==="click"&&e.target!==B)return;const q=P.value.trim();if(!q||!box())return;if(!command(q))return;e.preventDefault();e.stopImmediatePropagation();msg(q,"user");P.value=""};
B.addEventListener("click",capture,true);P.addEventListener("keydown",capture,true);
const css=document.createElement("style");css.textContent='.matrix-diagram{box-sizing:border-box!important}.matrix-chat-updated{animation:mxp .45s ease}@keyframes mxp{50%{outline:3px solid #6b8cff}}';document.head.appendChild(css);
})();
