(()=>{
  const $=id=>document.getElementById(id);
  const app=$('appRoot'),editor=$('editor'),prompt=$('prompt'),overlay=$('overlay'),sidebar=document.querySelector('.sidebar');
  const API=(window.CONFIG_API||'https://word-dkng.onrender.com').replace(/\/+$/,'');
  let autoSave=localStorage.getItem('aiws-autosave')!=='0', theme=localStorage.getItem('aiws-theme')||'light', focus=false, searchMatches=[], searchIndex=0;
  const toast=(text,type='')=>{const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=text;$('toastStack').appendChild(e);setTimeout(()=>e.remove(),3000)};
  const api=p=>API+p;
  const words=()=>String(editor?.innerText||'').trim().split(/\s+/).filter(Boolean).length;
  function stats(){const text=String(editor?.innerText||'').replace(/\u00a0/g,' ').trim(),w=words(),c=text.length,mins=w?Math.max(1,Math.ceil(w/180)):0;const sentences=(text.match(/[.!?]/g)||[]).length;const heads=editor?.querySelectorAll('h2,h3').length||0;const score=w?Math.min(100,Math.round(Math.min(45,w/8)+Math.min(25,(new Set(text.toLowerCase().split(/\s+/))).size/4)+Math.min(20,sentences/2)+heads*5)):0;$('wordCount').textContent=`${w} so‘z`;$('charCount').textContent=`${c} belgi`;$('readTime').textContent=`${mins} daqiqa o‘qish`;$('wordCountSide').textContent=w;$('charCountSide').textContent=c;$('readTimeSide').textContent=mins;$('scoreValue').textContent=`${score}/100`;$('scoreBar').style.width=`${score}%`}
  function setTheme(){app.classList.toggle('dark',theme==='dark');$('themeToggle').textContent=theme==='dark'?'☀️ Yorug‘':'☾ Tungi'}
  async function createNew(){try{if(typeof status==='function')status('Yangi Word yaratilmoqda...');const r=await fetch(api('/api/create'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:'Yangi AI hujjat.docx'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Yangi hujjat yaratilmadi');currentDocumentId=d.documentId;currentFileName=d.fileName;currentFileHandle=null;rememberFile(d.fileName);clearEditor();$('docTitle').textContent='Yangi AI hujjat';$('updatedTime').textContent='Bugun · yangi';if(typeof status==='function')status('Tayyor');stats();toast('Yangi Word hujjati tayyor','success');}catch(e){toast(e.message,'error');if(typeof status==='function')status('Server xatosi')}}
  async function favorite(){if(!currentDocumentId){toast('Avval Word hujjat yarating yoki oching','error');return}try{const r=await fetch(api(`/api/files/${encodeURIComponent(currentDocumentId)}/favorite`),{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xatolik');currentFavorite=d.favorite;$('favoriteBtn').textContent=currentFavorite?'★':'☆';$('favoriteBtn').classList.toggle('active',currentFavorite);toast(currentFavorite?'Sevimliga qo‘shildi':'Sevimlidan olib tashlandi','success');}catch(e){toast(e.message,'error')}}
  function openSettings(){document.querySelectorAll('.modal').forEach(x=>x.hidden=true);$('settingsModal').hidden=false;overlay.hidden=false}
  function closePanels(){overlay.hidden=true;$('settingsModal').hidden=true;$('templateModal').hidden=true;if($('filesPanel'))$('filesPanel').setAttribute('aria-hidden','true');sidebar?.classList.remove('open')}
  function showFiles(mode='files'){if($('filesPanel'))$('filesPanel').setAttribute('aria-hidden','false');overlay.hidden=false;if(typeof loadRecents==='function')loadRecents(mode);}
  function openSearch(){const f=$('findBar');f.hidden=false;$('findInput').focus();search()}
  function clearMarks(){editor.querySelectorAll('mark.search-hit').forEach(m=>m.replaceWith(document.createTextNode(m.textContent||'')));searchMatches=[];searchIndex=0}
  function search(){clearMarks();const q=$('findInput').value.trim();if(!q){$('findCount').textContent='0 ta';return}const esc=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),re=new RegExp(esc,'gi'),walker=document.createTreeWalker(editor,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(!re.test(n.nodeValue||''))return;re.lastIndex=0;const f=document.createDocumentFragment();let last=0,m;const t=n.nodeValue||'';while((m=re.exec(t))){f.append(t.slice(last,m.index));const mark=document.createElement('mark');mark.className='search-hit';mark.textContent=m[0];f.append(mark);last=m.index+m[0].length}f.append(t.slice(last));n.parentNode.replaceChild(f,n)});searchMatches=[...editor.querySelectorAll('mark.search-hit')];$('findCount').textContent=`${searchMatches.length} ta`;searchIndex=0;focusMatch()}
  function focusMatch(){searchMatches.forEach(m=>m.classList.remove('search-current'));const m=searchMatches[searchIndex];if(m){m.classList.add('search-current');m.scrollIntoView({behavior:'smooth',block:'center'})}}
  function stepSearch(n){if(!searchMatches.length)return;searchIndex=(searchIndex+n+searchMatches.length)%searchMatches.length;focusMatch()}
  function templates(){const items=[['📄','Insho / esse','Maktab uchun kuchli, tartibli insho.','Mavzu: [mavzu]. Kuchli o‘zbekcha insho yoz: sarlavha, kirish, 3 ta dalil, misol va xulosa.'],['💼','CV / Resume','Professional rezyume strukturasi.','Professional CV yoz: profil, ko‘nikmalar, ta’lim, tajriba, loyihalar, yutuqlar. Yetishmagan joylarni [kiriting] bilan belgila.'],['📊','Loyiha hisoboti','Natijalar va keyingi qadamlar.','Loyiha hisoboti yoz: maqsad, bajarilgan ishlar, natijalar, muammolar, yechimlar va keyingi qadamlar.'],['🎓','Konspekt','Darsni tez takrorlash uchun.','Dars konspekti tayyorla: asosiy tushunchalar, sodda izohlar, 3 ta misol va 5 ta nazorat savoli.'],['🚀','Startup pitch','G‘oyani ta’sirli taqdim etish.','Startup pitch yoz: muammo, yechim, kim uchun, ustunlik, biznes modeli va yakuniy chaqiriq.'],['🧠','AI reja','G‘oyani amaliy loyihaga aylantirish.','Mening g‘oyam uchun reja tuz: maqsad, bosqichlar, resurslar, muddatlar, xavflar va KPI. G‘oya: [yozing].']];$('templateGrid').innerHTML=items.map((x,i)=>`<button class="template-card" data-i="${i}"><div class="template-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></button>`).join('');$('templateGrid').querySelectorAll('.template-card').forEach((b,i)=>b.onclick=()=>{prompt.value=items[i][3];$('templateModal').hidden=true;overlay.hidden=true;prompt.focus();toast('Andoza AI topshirig‘iga joylandi')})}
  async function check(){try{const r=await fetch(api('/health'),{cache:'no-store'});const d=await r.json();$('healthDot').className='health-dot '+(d.ok?'online':'offline');$('healthText').textContent=d.aiConfigured?`AI on · ${d.provider}`:'API on';$('serverInfo').textContent=`${d.provider} · ${d.model}`;$('serverPill').textContent=d.aiConfigured?'ONLINE':'AI OFF';$('serverPill').classList.toggle('ok',Boolean(d.aiConfigured))}catch{$('healthDot').className='health-dot offline';$('healthText').textContent='API offline';$('serverInfo').textContent='Server bilan aloqa yo‘q';$('serverPill').textContent='OFFLINE'}}
  async function silentSave(){if(!autoSave||!currentDocumentId||typeof serialiseContent!=='function')return;try{await fetch(api('/api/save'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:currentDocumentId,content:serialiseContent()})});if(typeof status==='function')status('Avto-saqlangan')}catch{}}
  function wire(){
    setTheme();$('autosaveToggle').checked=autoSave;stats();check();
    $('newBtn').onclick=e=>{e.preventDefault();createNew()};$('favoriteBtn').onclick=favorite;
    $('focusBtn').onclick=()=>{focus=!focus;app.classList.toggle('focus',focus);$('focusBtn').textContent=focus?'◒ Fokusdan chiqish':'◒ Fokus'};
    $('searchBtn').onclick=openSearch;$('findClose').onclick=()=>{clearMarks();$('findBar').hidden=true};$('findInput').oninput=search;$('findNext').onclick=()=>stepSearch(1);$('findPrev').onclick=()=>stepSearch(-1);
    $('templatesBtn').onclick=()=>{$('templateModal').hidden=false;overlay.hidden=false;templates()};$('insertTemplateBtn').onclick=()=>{$('templateModal').hidden=false;overlay.hidden=false;templates()};$('closeTemplates').onclick=closePanels;
    $('closeSettings').onclick=closePanels;$('themeToggle').onclick=()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('aiws-theme',theme);setTheme()};$('autosaveToggle').onchange=e=>{autoSave=e.target.checked;localStorage.setItem('aiws-autosave',autoSave?'1':'0');toast(autoSave?'Avtomatik saqlash yoqildi':'Avtomatik saqlash o‘chirildi')};
    $('overlay').onclick=closePanels;$('closeFiles').onclick=closePanels;
    $('filesTopBtn').onclick=()=>showFiles('files');
    document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=e=>{e.preventDefault();document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='files'||v==='recent')showFiles('files');else if(v==='favorites')showFiles('favorites');else if(v==='templates'){$('templateModal').hidden=false;overlay.hidden=false;templates()}else if(v==='settings')openSettings();else closePanels()});
    editor.addEventListener('input',()=>{stats();if(autoSave&&currentDocumentId){clearTimeout(window.__studioSave);window.__studioSave=setTimeout(()=>{silentSave();toast('Avto-saqlash bajarildi','success')},2400)}});
    $('blockStyle').onchange=e=>{editor.focus();document.execCommand('formatBlock',false,e.target.value);stats()};
    document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();openSearch()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();prompt.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();createNew()}if(e.key==='Escape')closePanels()});
    window.addEventListener('beforeunload',e=>{if(currentDocumentId&&typeof dirty!=='undefined'&&dirty){e.preventDefault();e.returnValue=''}});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
